### PR TITLE
Exposing more functions

### PR DESCRIPTION
**Pull request by leafreynolds**
## Changes Proposed
Adding getters for the following:
- Fast return location - The last known location that a tardis was set to before beginning flight.
- Cooldown Ticks - the number of ticks that has passed since crashing.
- Cooldown duration - exposing how long until the tardis has finished cooling down after a crash
- isEventInComboTime - let a user know they can get a bonus for successfully completing an event before the combo timer is up
- getControlRequestCooldown - Get the current remaining ticks of cooldown between two controls, so they can know their grace period.

## Why
I would like these to have public accessors, to provide more information to the user in a ComputerCraft peripheral. More information is always a positive thing ♥

### CODE REVIEW

**Review by 50ap5ud5 — CHANGES_REQUESTED** [review]
Thanks for this leaf, good to hear from you again! Can you please add documentation about what the getter does and what value it provides?

**Comment by leafreynolds** [comment]
> Thanks for this leaf, good to hear from you again! Can you please add documentation about what the getter does and what value it provides?

Hey hey. When you say documentation, are you meaning adding it above the function? or adding more information to this pull request specifically. Very few of the functions in TardisRefined contain function documentation, but happy to add them if needed.

For me, the value that exposing private variables provides is largely geared towards exposing information for a computercraft peripheral addon. The more information we can access, the better ♥

**Comment by 50ap5ud5** [comment]
> > Thanks for this leaf, good to hear from you again! Can you please add documentation about what the getter does and what value it provides?
> 
> Hey hey. When you say documentation, are you meaning adding it above the function? or adding more information to this pull request specifically. Very few of the functions in TardisRefined contain function documentation, but happy to add them if needed.
> 
> For me, the value that exposing private variables provides is largely geared towards exposing information for a computercraft peripheral addon. The more information we can access, the better ♥

Documentation in the relevant java files in the form of comments, please. Yes, many of our functions are undocumented, it's an unfortunate side effect of the mod moving so fast from a prototype to a functional release without much cleanup so far. Helpings us with this would be appreciated. We are also looking to refactor things and document functions going forward in 1.20, but that has not been released yet. 

A summary of getters you added in this PR's description would be great too. Thanks!

**Comment by Suff99** [comment]
I am happy to approve this if @50ap5ud5 is

**Review by 50ap5ud5 — APPROVED** [review]
Changes look good now, nice work!

**Pull request merged**
